<a href="https://colab.research.google.com/github/sayja-yug/flyrank-ml/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sayja-yug/flyrank-ml/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window
Unit of Analysis

For the Refresh / Content Opportunity Scoring lane, one row represents the daily performance of a single content page. Each row contains measurements such as search traffic, clicks, impressions, rankings, and other SEO-related signals for one content item on one specific date. This daily grain allows the model to evaluate how the performance of each page changes over time and identify which pages are the strongest candidates for a content refresh.

Time Window

For feature development and analysis, I will use a mid-panel month (March 2026) instead of the final month in the dataset. Using a mid-panel month reflects the information that would have been available at the decision time and avoids introducing future information into the training process. The final month (June 2026) will be treated as a held-out period and not used for developing labels or features.

In [1]:
# ============================================================
# Install required packages
# ============================================================
!pip -q install datasets huggingface_hub pyarrow pandas

# ============================================================
# Import libraries
# ============================================================
from google.colab import userdata
from datasets import load_dataset
import pandas as pd

# ============================================================
# Read Hugging Face Token from Colab Secrets
# ============================================================
HF_TOKEN = userdata.get("HF_TOKEN")

if HF_TOKEN is None:
    raise ValueError("HF_TOKEN Secret not found. Please add it in Colab Secrets.")

print("✅ Hugging Face Token Loaded Successfully")

# ============================================================
# Load FlyRank Warehouse Dataset
# ============================================================
dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    split="train",
    token=HF_TOKEN
)

print("✅ Dataset Downloaded")

# ============================================================
# Convert to Pandas DataFrame
# ============================================================
df = dataset.to_pandas()

print("Original Shape:", df.shape)

# ============================================================
# Convert report_date to datetime
# ============================================================
df["report_date"] = pd.to_datetime(df["report_date"])

# ============================================================
# Filter to March 2026 (Mid-panel Month)
# ============================================================
march_df = df[
    (df["report_date"] >= "2026-03-01") &
    (df["report_date"] <= "2026-03-31")
].copy()

print("\n✅ March 2026 Data Loaded")
print("Shape:", march_df.shape)

# ============================================================
# Use March data as the working dataframe
# ============================================================
df = march_df

# ============================================================
# Preview Dataset
# ============================================================
display(df.head())

print("\nColumns:")
print(df.columns.tolist())

print("\nDate Range:")
print(df["report_date"].min(), "to", df["report_date"].max())

print("\nUnique Clients :", df["client_hash_id"].nunique())
print("Unique Content Pages :", df["content_hash_id"].nunique())

✅ Hugging Face Token Loaded Successfully

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

✅ Dataset Downloaded
Original Shape: (78835655, 30)

✅ March 2026 Data Loaded
Shape: (9841378, 30)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
35188099,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20.0,0.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188100,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188101,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125.0,1.0,616.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188102,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7.0,0.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188103,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11.0,0.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns:
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

Date Range:
2026-03-01 00:00:00 to 2026-03-31 00:00:00

Unique Clients : 55
Unique Content Pages : 331437

## 2. Fields: feature / label / context / excluded

## Feature

Features are the variables that are available at the moment a decision is made about improving a content page. These variables describe the current SEO performance and user engagement of the page.

Features used:

- gsc_impressions
- gsc_clicks
- gsc_avg_position
- gsc_sum_position
- ga4_pageviews
- ga4_sessions
- ga4_users
- ga4_engaged_sessions
- ga4_total_engagement_sec
- sessions_organic
- sessions_direct
- sessions_referral
- sessions_social
- sessions_paid
- sessions_ai
- scroll_events

These values are already known before making an optimization decision and therefore can safely be used as input features.

---

## Label

The label is the value the model will predict in the future.

For this project, I will predict future organic performance of a content page using historical Search Console and GA4 data.

Possible prediction target:

- Future Organic Sessions (sessions_organic)
or
- Future Google Search Clicks (gsc_clicks)

The label will always represent a future outcome rather than current performance.

---

## Context

Context fields identify the observation but should not directly influence the prediction.

Context fields:

- report_date
- client_hash_id
- content_hash_id
- client_has_gsc
- client_has_ga4
- gsc_data_available
- ga4_data_available

These columns describe when and where the data comes from.

---

## Excluded

Excluded fields are values that would create leakage or are unavailable when the prediction is made.

Examples include:

- Future month's clicks
- Future month's sessions
- Future engagement values
- Any information collected after the prediction date

These fields are intentionally excluded to prevent data leakage and ensure the model only learns from information available at decision time.

In [2]:
# ==============================
# SECTION 2 - Verify Field Groups
# ==============================

features = [
    "gsc_impressions",
    "gsc_clicks",
    "gsc_sum_position",
    "gsc_avg_position",
    "ga4_pageviews",
    "ga4_sessions",
    "ga4_users",
    "ga4_engaged_sessions",
    "ga4_total_engagement_sec",
    "sessions_organic",
    "sessions_direct",
    "sessions_referral",
    "sessions_social",
    "sessions_paid",
    "sessions_ai",
    "scroll_events"
]

context = [
    "report_date",
    "client_hash_id",
    "content_hash_id",
    "client_has_gsc",
    "client_has_ga4",
    "gsc_data_available",
    "ga4_data_available"
]

print("=" * 60)
print("FEATURE COLUMNS")
print("=" * 60)
print(features)

print("\nTotal Features:", len(features))

print("\n" + "=" * 60)
print("CONTEXT COLUMNS")
print("=" * 60)
print(context)

print("\nTotal Context Columns:", len(context))

print("\n" + "=" * 60)
print("Checking Columns")
print("=" * 60)

for col in features + context:
    print(f"{col:35} {'✅ Exists' if col in df.columns else '❌ Missing'}")

============================================================
FEATURE COLUMNS
============================================================
['gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'scroll_events']

Total Features: 16

============================================================
CONTEXT COLUMNS
============================================================
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available']

Total Context Columns: 7

============================================================
Checking Columns
============================================================
gsc_impressions                     ✅ Exists
gsc_clicks                          ✅ Exists
gsc_sum_position                    ✅ Exists
gsc_avg_position                    ✅ Exists
ga4_pageviews                       ✅ Exists
ga4_sessions                        ✅ Exists
ga4_users                           ✅ Exists
ga4_engaged_sessions                ✅ Exists
ga4_total_engagement_sec            ✅ Exists
sessions_organic                    ✅ Exists
sessions_direct                     ✅ Exists
sessions_referral                   ✅ Exists
sessions_social                     ✅ Exists
sessions_paid                       ✅ Exists
sessions_ai                         ✅ Exists
scroll_events                       ✅ Exists
report_date                         ✅ Exists
client_hash_id                      ✅ Exists
content_hash_id                     ✅ Exists
client_has_gsc                      ✅ Exists
client_has_ga4                      ✅ Exists
gsc_data_available                  ✅ Exists
ga4_data_available                  ✅ Exists

## 3. Verify it with queries (grain, counts, missing values, windows)
### Query 1 – Verify the Grain of the Dataset

The unit of analysis defined in Section 1 is:

**One row represents one content page for one client on one reporting day.**

To verify this assumption, I check whether the combination of:

- report_date
- client_hash_id
- content_hash_id

is unique for every row.

If duplicate combinations exist, then my assumed grain is incorrect.

If no duplicates exist, then the dataset follows the expected grain.

### Query 2 – Verify Row Count and Date Span

The assignment specifies working on a single mid-panel month (March 2026).

This query verifies that the working dataset contains only the intended time window.

It reports:

- Total number of rows
- Earliest reporting date
- Latest reporting date

This confirms that all later feature engineering is performed only on the selected month.

### Query 3 – Verify Data Availability

Not every row in the warehouse contains usable Search Console (GSC) or Google Analytics 4 (GA4) data.

Before building features, I verify how many rows remain after filtering for rows where both GSC and GA4 data are available.

This ensures that later feature engineering is performed only on valid observations rather than missing or incomplete records.

In [4]:
# =====================================================
# QUERY 1 : Verify Dataset Grain
# =====================================================

grain_columns = [
    "report_date",
    "client_hash_id",
    "content_hash_id"
]

# Total rows
total_rows = len(df)

# Unique grain combinations
unique_rows = df[grain_columns].drop_duplicates().shape[0]

# Duplicate rows
duplicate_rows = total_rows - unique_rows

print("=" * 60)
print("VERIFYING DATASET GRAIN")
print("=" * 60)

print(f"Total Rows                : {total_rows:,}")
print(f"Unique Grain Combinations : {unique_rows:,}")
print(f"Duplicate Rows            : {duplicate_rows:,}")

print()

if duplicate_rows == 0:
    print("✅ VERIFIED")
    print("Each row is uniquely identified by:")
    print("report_date + client_hash_id + content_hash_id")
else:
    print("❌ WARNING")
    print("Duplicate grain found.")
    print("The unit of analysis is NOT unique.")

# Show duplicate rows if they exist
if duplicate_rows > 0:
    print("\nDuplicate Examples:\n")
    display(
        df[df.duplicated(subset=grain_columns, keep=False)]
        .sort_values(grain_columns)
        .head(10)
    )


# =====================================================
# QUERY 2 : Verify Row Count and Date Span
# =====================================================

import pandas as pd

# Make sure report_date is datetime
df["report_date"] = pd.to_datetime(df["report_date"])

print("=" * 60)
print("VERIFYING WORKING TIME WINDOW")
print("=" * 60)

print(f"Total Rows        : {len(df):,}")

print()

print(f"Earliest Date     : {df['report_date'].min().date()}")

print(f"Latest Date       : {df['report_date'].max().date()}")

print()

print("Number of Unique Days :", df["report_date"].nunique())

print()

print("=" * 60)
print("Rows Per Date")
print("=" * 60)

display(
    df.groupby("report_date")
      .size()
      .reset_index(name="row_count")
)

# =====================================================
# QUERY 3 : Verify Data Availability
# =====================================================

print("=" * 60)
print("VERIFYING DATA AVAILABILITY")
print("=" * 60)

print("\nTotal Rows Before Filtering :", len(df))

# Keep only rows where BOTH data sources exist
available_df = df[
    (df["gsc_data_available"] == True) &
    (df["ga4_data_available"] == True)
]

print("\nTotal Rows After Filtering :", len(available_df))

print("\nRows Removed :", len(df) - len(available_df))

print("\nPercentage Remaining : {:.2f}%".format(
    (len(available_df) / len(df)) * 100
))

print("\nSample of Available Data")

display(
    available_df[
        [
            "report_date",
            "client_hash_id",
            "content_hash_id",
            "gsc_data_available",
            "ga4_data_available"
        ]
    ].head()
)

============================================================
VERIFYING DATASET GRAIN
============================================================
Total Rows                : 9,841,378
Unique Grain Combinations : 9,841,378
Duplicate Rows            : 0

✅ VERIFIED
Each row is uniquely identified by:
report_date + client_hash_id + content_hash_id
============================================================
VERIFYING WORKING TIME WINDOW
============================================================
Total Rows        : 9,841,378

Earliest Date     : 2026-03-01
Latest Date       : 2026-03-31

Number of Unique Days : 31

============================================================
Rows Per Date
============================================================

   report_date  row_count
0   2026-03-01     275874
1   2026-03-02     276269
2   2026-03-03     311676
3   2026-03-04     311675
4   2026-03-05     311676
5   2026-03-06     312187
6   2026-03-07     312387
7   2026-03-08     313374
8   2026-03-09     313874
9   2026-03-10     314047
10  2026-03-11     314232
11  2026-03-12     317742
12  2026-03-13     317900
13  2026-03-14     319584
14  2026-03-15     319758
15  2026-03-16     319924
16  2026-03-17     320048
17  2026-03-18     320682
18  2026-03-19     323054
19  2026-03-20     323738
20  2026-03-21     324296
21  2026-03-22     324476
22  2026-03-23     324899
23  2026-03-24     325117
24  2026-03-25     325605
25  2026-03-26     326039
26  2026-03-27     326193
27  2026-03-28     326193
28  2026-03-29     326193
29  2026-03-30     331230
30  2026-03-31     331436

============================================================
VERIFYING DATA AVAILABILITY
============================================================

Total Rows Before Filtering : 9841378

Total Rows After Filtering : 364347

Rows Removed : 9477031

Percentage Remaining : 3.70%

Sample of Available Data

,report_date,client_hash_id,content_hash_id,gsc_data_available,ga4_data_available
35202579,2026-03-01,client_65de48885f4ef01b,content_5c80451459c29b4a,True,True
35202847,2026-03-01,client_65de48885f4ef01b,content_b1f61fc81b28b2d4,True,True
35202867,2026-03-01,client_65de48885f4ef01b,content_e25ea7297a1dffd3,True,True
35202882,2026-03-01,client_65de48885f4ef01b,content_6b0149a80607dac3,True,True
35202954,2026-03-01,client_65de48885f4ef01b,content_62673eea26c31c17,True,True

## 4. Data limits
## Five Features for the Refresh Opportunity Model

### Feature 1 — gsc_impressions

Reason:
This feature measures how frequently a content page appears in Google Search results. It is available before making any refresh decision and helps identify pages with strong search visibility.

Available at decision time:
Yes. Search impressions are historical observations collected before the decision.

---

### Feature 2 — gsc_clicks

Reason:
This feature measures how many users clicked the page from Google Search. It reflects current user interest and content performance.

Available at decision time:
Yes. Click counts are already known when deciding whether to refresh the page.

---

### Feature 3 — gsc_avg_position

Reason:
Average search position indicates how well the page ranks in Google Search. Pages with poor rankings but high impressions may represent optimization opportunities.

Available at decision time:
Yes. Ranking information is available before the editor decides to update the content.

---

### Feature 4 — ga4_sessions

Reason:
Sessions measure how much traffic actually reaches the page. This complements Search Console metrics by showing user visits after clicking.

Available at decision time:
Yes. Historical GA4 sessions are available before the refresh decision.

---

### Feature 5 — scroll_events

Reason:
Scroll events provide a simple measure of user engagement with the content. Pages with poor engagement may benefit from content improvements.

Available at decision time:
Yes. Scroll activity is recorded before any future optimization work.

In [6]:
# =====================================================
# SECTION 4 : Feature Frame
# =====================================================

feature_columns = [
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position",
    "ga4_sessions",
    "scroll_events"
]

feature_df = df[feature_columns].copy()

print("=" * 60)
print("FEATURE FRAME")
print("=" * 60)

print("Shape:", feature_df.shape)

print()

display(feature_df.head())

print("\nSummary Statistics")
print("="*60)
print("Missing Values")
print("="*60)

print(feature_df.isnull().sum())

============================================================
FEATURE FRAME
============================================================
Shape: (9841378, 5)

,gsc_impressions,gsc_clicks,gsc_avg_position,ga4_sessions,scroll_events
35188099,20.0,0.0,3.350000,NaN,NaN
35188100,1.0,0.0,0.000000,NaN,NaN
35188101,125.0,1.0,4.928000,NaN,NaN
35188102,7.0,0.0,4.000000,NaN,NaN
35188103,11.0,0.0,2.272727,NaN,NaN

Summary Statistics
============================================================
Missing Values
============================================================
gsc_impressions           0
gsc_clicks                0
gsc_avg_position    6230317
ga4_sessions        3018741
scroll_events       3018741
dtype: int64

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.