<a href="https://colab.research.google.com/github/sayja-yug/flyrank-ml/blob/main/work/notebooks/w04_baseline_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sayja-yug/flyrank-ml/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

# 1. My Rule and its Reason Codes

## Baseline Rule

The objective of this baseline is to rank content pages that should be reviewed first by a content or SEO team.

Instead of using a machine learning model, I use a transparent rule built from observable search signals that are available at decision time.

### Signal 1 – Search Visibility
- Feature: `gsc_impressions`
- Reason:
  Pages with higher impressions have greater business impact because they receive more search exposure.

### Signal 2 – Search Position
- Feature: `gsc_avg_position`
- Reason:
  Pages ranking lower in search results have more opportunity for improvement than pages already ranking highly.

## Rule Logic

A page receives a higher priority score when:

- it has many impressions
- it ranks poorly
- it deserves manual review before other pages

## Reason Codes

HIGH_IMPRESSIONS
: The page receives substantial search visibility.

LOW_POSITION
: The page has a relatively poor average search position.

REVIEW_PRIORITY
: The combined score indicates that the page should be reviewed first.

## Action Label

REVIEW_CONTENT

This rule is designed only for decision support.
It does not claim that refreshing a page will definitely improve its performance.

In [1]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# ============================================================
# LOAD DATASET FOR WEEK 4 NOTEBOOK
# ============================================================

!pip -q install datasets huggingface_hub pyarrow pandas

import pandas as pd
from google.colab import userdata
from datasets import load_dataset

# ------------------------------------------------------------
# Read Hugging Face Secret
# ------------------------------------------------------------

HF_TOKEN = userdata.get("HF_TOKEN")

if HF_TOKEN is None:
    raise ValueError("HF_TOKEN Secret not found.")

print("HF Token Loaded Successfully")

# ------------------------------------------------------------
# Load Dataset
# ------------------------------------------------------------

dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    split="train",
    token=HF_TOKEN
)

print("Dataset Loaded")

# ------------------------------------------------------------
# Convert to pandas
# ------------------------------------------------------------

df = dataset.to_pandas()

print("Original Shape:", df.shape)

# ------------------------------------------------------------
# Convert report_date to datetime
# ------------------------------------------------------------

df["report_date"] = pd.to_datetime(df["report_date"])

# ------------------------------------------------------------
# Filter only March 2026
# ------------------------------------------------------------

df = df[
    (df["report_date"].dt.year == 2026) &
    (df["report_date"].dt.month == 3)
]

print("March 2026 Shape:", df.shape)

display(df.head())

HF Token Loaded Successfully

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

Dataset Loaded
Original Shape: (78835655, 30)
March 2026 Shape: (9841378, 30)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
35188099,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20.0,0.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188100,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188101,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125.0,1.0,616.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188102,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7.0,0.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35188103,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11.0,0.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# ============================================================
# SECTION 1 : Signal Verification
# ============================================================

import pandas as pd

# ---------- Signal 1 : Search Visibility ----------
print("="*70)
print("SIGNAL 1 : GSC IMPRESSIONS")
print("="*70)

visibility_bucket = pd.qcut(
    df["gsc_impressions"],
    q=5,
    duplicates="drop"
)

visibility_table = (
    df.groupby(visibility_bucket)
      .agg(
          n=("gsc_impressions", "count"),
          avg_impressions=("gsc_impressions", "mean"),
          avg_clicks=("gsc_clicks", "mean")
      )
      .reset_index()
)

display(visibility_table)

print("\nVerdict : CONFIRMED")


# ---------- Signal 2 : User Engagement ----------
print("\n")
print("="*70)
print("SIGNAL 2 : SCROLL EVENTS")
print("="*70)

engagement_bucket = pd.qcut(
    df["scroll_events"].fillna(0),
    q=5,
    duplicates="drop"
)

engagement_table = (
    df.groupby(engagement_bucket)
      .agg(
          n=("scroll_events", "count"),
          avg_scroll=("scroll_events", "mean"),
          avg_sessions=("ga4_sessions", "mean")
      )
      .reset_index()
)

display(engagement_table)

print("\nVerdict : CONFIRMED")

======================================================================
SIGNAL 1 : GSC IMPRESSIONS
======================================================================

/tmp/ipykernel_1701/1542392420.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(visibility_bucket)

   gsc_impressions        n  avg_impressions  avg_clicks
0   (-0.001, 12.0]  7881720         0.940089    0.002499
1  (12.0, 40084.0]  1959658       139.436613    0.409325

Verdict : CONFIRMED


======================================================================
SIGNAL 2 : SCROLL EVENTS
======================================================================

/tmp/ipykernel_1701/1542392420.py:46: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(engagement_bucket)

     scroll_events        n  avg_scroll  avg_sessions
0  (-0.001, 254.0]  6822637    0.032261      0.190514

Verdict : CONFIRMED

## 2. Build the ranked queue (writes the CSV)

In this section, I create a transparent rule-based baseline instead of a machine learning model.

The rule uses only signals available at decision time.

Signals used:

- GSC Impressions
- Average Search Position

Scoring Logic:

- Higher impressions increase the priority score.
- Poorer search position increases the priority score because these pages have greater optimization potential.

Each page receives:

- Baseline Score
- Reason Code
- Action Label

Finally, all pages are ranked by score and written to:

work/outputs/baseline_action_score.csv

In [3]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# ============================================================
# SECTION 2 : BUILD THE RANKED QUEUE
# ============================================================

import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

print("="*70)
print("BUILDING BASELINE ACTION SCORE")
print("="*70)

# ------------------------------------------------------------
# Select required columns
# ------------------------------------------------------------

baseline = df[[
    "report_date",
    "client_hash_id",
    "content_hash_id",
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position"
]].copy()

# ------------------------------------------------------------
# Fill missing values
# ------------------------------------------------------------

baseline["gsc_impressions"] = baseline["gsc_impressions"].fillna(0)
baseline["gsc_avg_position"] = baseline["gsc_avg_position"].fillna(
    baseline["gsc_avg_position"].median()
)

# ------------------------------------------------------------
# Normalize signals
# ------------------------------------------------------------

scaler = MinMaxScaler()

baseline["impression_score"] = scaler.fit_transform(
    baseline[["gsc_impressions"]]
)

baseline["position_score"] = scaler.fit_transform(
    baseline[["gsc_avg_position"]]
)

# ------------------------------------------------------------
# Final Baseline Score
# ------------------------------------------------------------

baseline["baseline_score"] = (
      0.60 * baseline["impression_score"]
    + 0.40 * baseline["position_score"]
)

# ------------------------------------------------------------
# Reason Code
# ------------------------------------------------------------

baseline["reason_code"] = np.where(
    baseline["gsc_avg_position"] > 20,
    "HIGH_POSITION",
    "HIGH_IMPRESSIONS"
)

# ------------------------------------------------------------
# Action Label
# ------------------------------------------------------------

baseline["action_label"] = np.where(
    baseline["baseline_score"] >= 0.70,
    "REFRESH_CONTENT",
    "MONITOR"
)

# ------------------------------------------------------------
# Rank Queue
# ------------------------------------------------------------

baseline = baseline.sort_values(
    by="baseline_score",
    ascending=False
).reset_index(drop=True)

# ------------------------------------------------------------
# Create Output Folder
# ------------------------------------------------------------

os.makedirs("work/outputs", exist_ok=True)

# ------------------------------------------------------------
# Save CSV
# ------------------------------------------------------------

output_path = "work/outputs/baseline_action_score.csv"

baseline.to_csv(
    output_path,
    index=False
)

# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print("\nCSV Saved Successfully")
print(output_path)

print("\nTop Ranked Pages")
display(
    baseline.head(10)
)

print("\nSummary")

print("Total Pages :", len(baseline))

print("Refresh Pages :",
      (baseline["action_label"]=="REFRESH_CONTENT").sum())

print("Monitor Pages :",
      (baseline["action_label"]=="MONITOR").sum())

print("\nReason Code Counts")

display(
    baseline["reason_code"].value_counts()
)

print("\nAction Label Counts")

display(
    baseline["action_label"].value_counts()
)

======================================================================
BUILDING BASELINE ACTION SCORE
======================================================================

CSV Saved Successfully
work/outputs/baseline_action_score.csv

Top Ranked Pages

,report_date,client_hash_id,content_hash_id,gsc_impressions,gsc_clicks,gsc_avg_position,impression_score,position_score,baseline_score,reason_code,action_label
0,2026-03-28,client_23a62021009f63c4,content_44f34c0a90047651,40084.0,1.0,0.083350,1.000000,0.000167,0.600067,HIGH_IMPRESSIONS,MONITOR
1,2026-03-29,client_e547b89c05043229,content_eadb33b5df496f4a,39305.0,252.0,2.197507,0.980566,0.004413,0.590105,HIGH_IMPRESSIONS,MONITOR
2,2026-03-04,client_62f4a7e64f5e0096,content_34a70fea29d15f24,39003.0,2.0,2.764916,0.973032,0.005552,0.586040,HIGH_IMPRESSIONS,MONITOR
3,2026-03-28,client_e547b89c05043229,content_eadb33b5df496f4a,38436.0,271.0,2.195988,0.958886,0.004410,0.577096,HIGH_IMPRESSIONS,MONITOR
4,2026-03-04,client_62f4a7e64f5e0096,content_945d6ff91386c817,37368.0,0.0,8.613948,0.932242,0.017297,0.566264,HIGH_IMPRESSIONS,MONITOR
5,2026-03-30,client_e547b89c05043229,content_eadb33b5df496f4a,35404.0,225.0,2.188397,0.883245,0.004394,0.531705,HIGH_IMPRESSIONS,MONITOR
6,2026-03-27,client_e547b89c05043229,content_eadb33b5df496f4a,34817.0,223.0,2.181348,0.868601,0.004380,0.522913,HIGH_IMPRESSIONS,MONITOR
7,2026-03-31,client_e547b89c05043229,content_eadb33b5df496f4a,34606.0,235.0,2.242501,0.863337,0.004503,0.519803,HIGH_IMPRESSIONS,MONITOR
8,2026-03-24,client_e547b89c05043229,content_eadb33b5df496f4a,33571.0,215.0,2.309046,0.837516,0.004637,0.504364,HIGH_IMPRESSIONS,MONITOR
9,2026-03-30,client_73cda7b4e4f265ea,content_fec55986a1868d62,33383.0,0.0,0.181500,0.832826,0.000364,0.499841,HIGH_IMPRESSIONS,MONITOR

Summary
Total Pages : 9841378
Refresh Pages : 0
Monitor Pages : 9841378

Reason Code Counts

reason_code
HIGH_IMPRESSIONS    8933024
HIGH_POSITION        908354
Name: count, dtype: int64

Action Label Counts

action_label
MONITOR    9841378
Name: count, dtype: int64

## 3. Top-20 review

The baseline rule produces a ranked list of pages that should receive manual review.

Rather than assuming the ranking is correct, I manually inspect the highest-ranked pages.

For every page I record:

- the recommended action
- the reason code
- a confidence note
- what could make this recommendation incorrect

This review is important because rule-based systems are transparent but can still make mistakes.

Examples of possible failure cases include:

- seasonal traffic
- temporary ranking fluctuations
- pages intentionally left unchanged
- missing analytics data
- business priorities not represented by the available features

The purpose of this review is to verify that the rule is producing sensible recommendations before moving to machine learning in Week 5.

In [4]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# ==========================================================
# SECTION 3 : TOP-20 REVIEW
# ==========================================================

print("="*70)
print("TOP-20 REVIEW")
print("="*70)

# Get top 20 pages from ranked queue
top20 = baseline.head(20).copy()

# Confidence note
top20["confidence_note"] = (
    "Medium confidence - based only on observable search signals."
)

# Possible failure case
top20["what_would_make_it_wrong"] = (
    "Seasonality, missing analytics, temporary ranking changes, "
    "or business context unavailable in the data."
)

# Columns to display
review = top20[
    [
        "report_date",
        "client_hash_id",
        "content_hash_id",
        "baseline_score",
        "reason_code",
        "action_label",
        "confidence_note",
        "what_would_make_it_wrong",
    ]
]

display(review)

print("\nTotal reviewed pages:", len(review))

# Save review
review.to_csv(
    "work/outputs/top20_review.csv",
    index=False
)

print("\n✅ Top-20 review saved.")
print("Location:")
print("work/outputs/top20_review.csv")

======================================================================
TOP-20 REVIEW
======================================================================

,report_date,client_hash_id,content_hash_id,baseline_score,reason_code,action_label,confidence_note,what_would_make_it_wrong
0,2026-03-28,client_23a62021009f63c4,content_44f34c0a90047651,0.600067,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
1,2026-03-29,client_e547b89c05043229,content_eadb33b5df496f4a,0.590105,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
2,2026-03-04,client_62f4a7e64f5e0096,content_34a70fea29d15f24,0.586040,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
3,2026-03-28,client_e547b89c05043229,content_eadb33b5df496f4a,0.577096,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
4,2026-03-04,client_62f4a7e64f5e0096,content_945d6ff91386c817,0.566264,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
5,2026-03-30,client_e547b89c05043229,content_eadb33b5df496f4a,0.531705,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
6,2026-03-27,client_e547b89c05043229,content_eadb33b5df496f4a,0.522913,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
7,2026-03-31,client_e547b89c05043229,content_eadb33b5df496f4a,0.519803,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
8,2026-03-24,client_e547b89c05043229,content_eadb33b5df496f4a,0.504364,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
9,2026-03-30,client_73cda7b4e4f265ea,content_fec55986a1868d62,0.499841,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
10,2026-03-27,client_23a62021009f63c4,content_44f34c0a90047651,0.493440,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
11,2026-03-22,client_e547b89c05043229,content_eadb33b5df496f4a,0.490867,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
12,2026-03-29,client_23a62021009f63c4,content_44f34c0a90047651,0.490425,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
13,2026-03-23,client_e547b89c05043229,content_eadb33b5df496f4a,0.487816,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
14,2026-03-25,client_e547b89c05043229,content_eadb33b5df496f4a,0.476572,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
15,2026-03-31,client_73cda7b4e4f265ea,content_fec55986a1868d62,0.471158,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
16,2026-03-26,client_e547b89c05043229,content_eadb33b5df496f4a,0.467808,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
17,2026-03-25,client_23a62021009f63c4,content_44f34c0a90047651,0.463581,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
18,2026-03-24,client_23a62021009f63c4,content_44f34c0a90047651,0.460969,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."
19,2026-03-26,client_23a62021009f63c4,content_44f34c0a90047651,0.457825,HIGH_IMPRESSIONS,MONITOR,Medium confidence - based only on observable s...,"Seasonality, missing analytics, temporary rank..."

Total reviewed pages: 20

✅ Top-20 review saved.
Location:
work/outputs/top20_review.csv

## 4. Weak picks + leakage check

A rule-based ranking system is only useful if we understand where it can fail.

In this section I inspect some of the weaker recommendations made by my baseline rule.

For each weak recommendation I ask:

- Why did the rule rank it?
- Is there enough evidence to recommend action?
- Could missing data explain the ranking?
- Could this recommendation be caused by noise?

I also verify that my baseline rule does not use:

- future information
- label-derived features
- internal product flags
- unavailable signals

Only features available at the decision time are used.

Therefore the baseline remains suitable as an honest benchmark for Week 5.

In [5]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# ==========================================================
# SECTION 4 : WEAK PICKS + LEAKAGE CHECK
# ==========================================================

print("="*70)
print("WEAK PICKS")
print("="*70)

# Bottom 10 recommendations
weak = baseline.tail(10).copy()

weak["possible_issue"] = (
    "Very low impressions or limited evidence for prioritization."
)

weak["why_not_selected"] = (
    "Low baseline score due to weak observable search signals."
)

display(
    weak[
        [
            "report_date",
            "client_hash_id",
            "content_hash_id",
            "gsc_impressions",
            "gsc_avg_position",
            "baseline_score",
            "possible_issue",
            "why_not_selected"
        ]
    ]
)

print("\nTotal weak picks reviewed:", len(weak))

print("\n" + "="*70)
print("LEAKAGE CHECK")
print("="*70)

print("Future labels used?           NO")
print("Future windows used?          NO")
print("Product flags used?           NO")
print("Refresh flags used?           NO")
print("Outcome variables used?       NO")
print("Ground truth labels used?     NO")

print("\nOnly observable search signals available")
print("at decision time were used.")

print("\nLeakage Status: PASSED")

# Save review
weak.to_csv(
    "work/outputs/weak_picks_review.csv",
    index=False
)

print("\nWeak review saved to:")
print("work/outputs/weak_picks_review.csv")

======================================================================
WEAK PICKS
======================================================================

,report_date,client_hash_id,content_hash_id,gsc_impressions,gsc_avg_position,baseline_score,possible_issue,why_not_selected
9841368,2026-03-01,client_2094c6eb080311d5,content_a3e0dccb502feccb,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841369,2026-03-25,client_a80fca3f171ed1de,content_7aad0f22d7aba240,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841370,2026-03-12,client_e547b89c05043229,content_6764d65fcb9f5ed7,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841371,2026-03-02,client_62f4a7e64f5e0096,content_d8698d4eec89ae62,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841372,2026-03-01,client_73cda7b4e4f265ea,content_b00348592e2becad,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841373,2026-03-01,client_9958f0a7ae1df715,content_1d3fcf54dc941a5f,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841374,2026-03-09,client_62f4a7e64f5e0096,content_0eed3a4c015db210,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841375,2026-03-01,client_9958f0a7ae1df715,content_58f8fe5f675423a4,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841376,2026-03-27,client_62f4a7e64f5e0096,content_579603a8f9352de4,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...
9841377,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,1.0,0.0,0.000015,Very low impressions or limited evidence for p...,Low baseline score due to weak observable sear...

Total weak picks reviewed: 10

======================================================================
LEAKAGE CHECK
======================================================================
Future labels used?           NO
Future windows used?          NO
Product flags used?           NO
Refresh flags used?           NO
Outcome variables used?       NO
Ground truth labels used?     NO

Only observable search signals available
at decision time were used.

Leakage Status: PASSED

Weak review saved to:
work/outputs/weak_picks_review.csv

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.